# Generated by Django 5.1.7 on 2025-04-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
