# Generated by Django 5.1.7 on 2025-04-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user_profile_images/'),
        ),
    ]
