# Generated by Django 5.1.7 on 2025-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_remove_profile_image_user_document_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document_image',
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_citizenships/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_licenses/'),
        ),
    ]
