# Generated by Django 5.1.7 on 2025-04-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorderitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.product'),
        ),
    ]
