# Generated by Django 5.1.7 on 2025-04-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rentorderitems_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wishlist'},
        ),
        migrations.RemoveField(
            model_name='rentorderitems',
            name='product',
        ),
    ]
