# Generated by Django 5.1.7 on 2025-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_vendor_options_alter_product_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document_image',
            field=models.ImageField(blank=True, default='document.jpg', upload_to='documents/'),
        ),
    ]
