# Generated by Django 5.1.7 on 2025-04-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_product_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='document_image',
        ),
        migrations.CreateModel(
            name='ProductDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_image', models.ImageField(default='document.jpg', upload_to='product-documents')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_documents', to='Home.product')),
            ],
            options={
                'verbose_name_plural': 'Product Documents',
            },
        ),
    ]
