# Generated by Django 5.1.7 on 2025-04-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_product_document_image_productdocuments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDocuments',
        ),
    ]
