# Generated by Django 5.1.4 on 2025-03-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numberp',
            field=models.CharField(blank=True, default='ga 1 pa 1111', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=1),
        ),
    ]
