# Generated by Django 5.1.4 on 2025-03-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_product_numberp_product_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='authentic_rating',
            field=models.CharField(blank=True, default='100', max_length=100, null=True),
        ),
    ]
