# Generated by Django 5.1.7 on 2025-04-22 15:30

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_productimages_date_alter_productimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='product-images'),
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_image', models.ImageField(default='terms.jpg', upload_to='product-images')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='Home.product')),
            ],
            options={
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
    ]
