# Generated by Django 5.1.7 on 2025-03-26 13:40

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_vendor_authentic_rating'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
