# Generated by Django 5.1.7 on 2025-04-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_documentimage_document_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='doc_image',
            field=models.ImageField(default='doc.jpg', upload_to='product-images'),
        ),
    ]
