# Generated by Django 5.1.7 on 2025-04-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_address_user_alter_documentimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentimage',
            name='doc_image',
        ),
    ]
