# Generated by Django 5.1.7 on 2025-04-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_remove_documentimage_doc_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
    ]
