# Generated by Django 5.1.7 on 2025-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
