# Generated by Django 5.1.7 on 2025-04-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_alter_vendor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numberp',
            new_name='numberplate',
        ),
    ]
