# Generated by Django 5.1.7 on 2025-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_rename_numberp_product_numberplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorder',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
