# Generated by Django 5.1.7 on 2025-05-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_rentorder_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorderitems',
            name='rent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentorderitems',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
