# Generated by Django 5.1.7 on 2025-05-15 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_rentorderitems_rent_date_rentorderitems_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorderitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.product'),
        ),
    ]
